name: 'Deploy'

on:
  push:
    branches:
      - main
    paths:
      - "svelte-app/**"
  workflow_dispatch:


defaults:
  run:
    working-directory: svelte-app

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [
          "nginx",
          "sveltekit"
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}

      # ECR ログイン
      - name: ECR login
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      - name: Update nginx parameters
        run:
          sed -i -e "s/sveltekit:3000/localhost:3000/g" docker/nginx/default.conf

      # Docker image のビルドとプッシュ
      # matrix を使って複数の docker image をビルド
      # uses の場合、working-directory は使えないのでフルパス指定
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./svelte-app
          file: ./svelte-app/docker/${{ matrix.target }}/Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ matrix.target }}:${{ github.sha }}, ${{ steps.login-ecr.outputs.registry }}/${{ matrix.target }}::${{ github.sha }}

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}

      - name: Setup ecspresso
        uses: kayac/ecspresso@v2

      - name: Deploy
        env:
          CLUSTER_NAME: "practice-svelte-fargate"
          TFC_ORGANIZATION: ${{ vars.TFC_ORGANIZATION }}
          TFC_WORKSPACE: ${{ vars.TFC_WORKSPACE }}
          TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
        run: |
          ecspresso deploy --config ./deployment/ecspresso/practice-svelte-fargate/config.yml
