name: 'Deploy'

on:
  workflow_dispatch:


defaults:
  run:
    working-directory: svelte-app

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}

      - name: Setup ecspresso
        uses: kayac/ecspresso@v2

      - name: Rollback
        env:
          CLUSTER_NAME: "practice-svelte-fargate"
          TFC_ORGANIZATION: ${{ vars.TFC_ORGANIZATION }}
          TFC_WORKSPACE: ${{ vars.TFC_WORKSPACE }}
          TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
        run: |
          ecspresso rollback --config ./deployment/ecspresso/practice-svelte-fargate/config.yml --dry-run
